// This file was initially generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6

package oasis.names.tc.saml._2_0.assertion_;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;

import com.rsa.names._2009._12.std_ext.saml2_.RenewRestrictionType;

import oasis.names.tc.saml._2_0.conditions.delegation_.DelegationRestrictionType;

/**
 * Java class for ConditionAbstractType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ConditionAbstractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionAbstractType")
@XmlSeeAlso({
    ProxyRestrictionType.class,
    AudienceRestrictionType.class,
    RenewRestrictionType.class,
    DelegationRestrictionType.class
})
public abstract class ConditionAbstractType {}
